name: CI/CD Pipeline for Fashion MNIST

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Run flake8
        run: |
          flake8 .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pytest tensorflow

      - name: Run tests
        run: |
          pytest tests/

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t eu.gcr.io/gcp-learn-430710/fashion-mnist:$GITHUB_SHA .

      - name: Authenticate with GCP
        run: |
          echo "${{ secrets.GCP_KEY }}" | base64 --decode > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud auth configure-docker --quiet
        env:
          GCP_PROJECT_ID: gcp-learn-430710

      - name: Push Docker image to GCR
        run: |
          docker push eu.gcr.io/gcp-learn-430710/fashion-mnist:$GITHUB_SHA