name: CI/CD Pipeline for Fashion MNIST

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install flake8
      - name: Run flake8
        run: |
          flake8 .
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pytest tensorflow
      - name: Run tests
        run: |
          pytest

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t gcr.io/gcp-learn-430710/fashion-mnist:$GITHUB_SHA .
      - name: Push Docker image to GCR
        run: |
          echo ${{ secrets.GCP_KEY }} | docker login -u _json_key --password-stdin https://gcr.io
          docker push gcr.io/gcp-learn-430710/fashion-mnist:$GITHUB_SHA
        env:
          GCP_PROJECT_ID: gcp-learn-430710
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy Docker image to GCS
        run: |
          gsutil cp gs://gcr.io/gcp-learn-430710/fashion-mnist:$GITHUB_SHA gs://cicd-on-gcp/
        env:
          GCP_PROJECT_ID: gcp-learn-430710
